schema_version = "1.0.0"

id = "cubemap_renderer"
version = "1.5.1"
name = "Cubemap Renderer"
tagline = "Render cubemaps for UE5 and Unity"
maintainer = "Igor Unguryanov"
type = "add-on"
website = "https://github.com/Igrom4ik/Cubemap_Creator"
tags = ["Render", "Game Engine"]
license = ["GPL-3.0-or-later"]
blender_version_min = "5.0.0"

[permissions]
network = "https://pypi.org/*, https://files.pythonhosted.org/*"
files = "all"
python_files = "all"

